### PR TITLE
fix: align single code block with the buttons

### LINKED ISSUE #2148: blog: single line code blocks look imbalanced
### Preliminary Checks

- [X] I have reviewed https://unkey.com/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Is your feature request related to a problem? Please describe.

image
source: https://www.unkey.com/blog/fixing-serverless-with-a-vps

I guess it's cause the line is not vertically centered, but maybe we should just make everything items-center with the icons?

like:

`const x = 1 [copybutton] [downloadbutton]`

### Describe the solution

For single line code blocks, we should show a much narrower block and have the buttons in line if possible

### Describe alternatives you have considered (if any)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DeepaPrasanna**
## What does this PR do?

Updated styles to align the single line code block with the buttons.

Fixes #2148

Before:
image

After:
image

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Visit the [blog](https://www.unkey.com/blog/fixing-serverless-with-a-vps) the single line code block should be vertically center aligned with the buttons.

### Required

- [x] Filled out the "How to test" section in this PR
- [ ] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand areas
- [ ] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Improved layout and organization of the code block component in the blog.
	- Enhanced visual alignment of code display and action buttons.
	- Introduced conditional rendering for code blocks based on content length.
	- Added a key prop to enhance rendering efficiency in the suggested blogs component.

- **Bug Fixes**
	- Streamlined structure for the download button and copy functionality.

- **Documentation**
	- Added a new README file for the "@unkey/api" package to enhance user understanding and usability.

- **Refactor**
	- Restructured JSX layout for better maintainability and clarity.
	- Updated API definitions for improved clarity and consistency in error handling.

### CODE REVIEW

**Review by perkinsjr — CHANGES_REQUESTED** [review]
This change made all codeblock buttons misaligned 

image

**Comment by DeepaPrasanna** [comment]
I fixed that for above single line code block. 
Before:
image

After applying the styles: 
image

After applying the styles in corrected way:
image

But, there is one thing that I noticed. It seems all the code blocks are using `BlogCodeBlockSingle`. I thought only single line code block is using that. That is why the styles have been updated to multi line code block too. 
image
 It seems the code block in the markdown is being converted to `pre` tags and thus using only the `BlogCodeBlockSingle`

**Review by perkinsjr — CHANGES_REQUESTED** [review]
This code changes the core functionality. 

In our current code we have two types of code blocks.

1. A single code block.
2. A code block that has multiple tabs.

The 2nd one allows a developer to add to do examples in multiple languages in a single code block with clickable tabs.

We only want to fix a single line of code when in either of these codeblocks to have correct alignment. 

What you currently have done. Is now made all code blocks into tab based code blocks. Which in turn has now changed how all of the posts / changelogs and / templates work. 

All that is required for this change is:

1. Look for a single line in a code block and fix alignment.
2. Make sure if there are more than one line of code in a codeblock that the copy and the download buttons don't shift.

No other changes are required outside of that, although fixing the key on the blog is welcomed.

Please make sure you are testing locally on all screen sizes, in the blog, changelog.

**Comment by DeepaPrasanna** [comment]
I am sorry. It was misunderstanding on my part.

**Pull request merged**
