### PR TITLE
fix: control overflow of desktop sidebar.

### LINKED ISSUE #481: [KEY-254] Cap list of apis and add a scrollbar before it overflows the user button
<sub>From [SyncLinear.com](https://synclinear.com) | [KEY-254](https://linear.app/unkey/issue/KEY-254/cap-list-of-apis-and-add-a-scrollbar-before-it-overflows-the-user)</sub>

### PR DESCRIPTION
**Pull request by spiritanand**
## Type of change

- [X] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation

### Before this PR

image

### After this PR

image

Closes #481

### CODE REVIEW

**Comment by spiritanand** [comment]
@chronark should I make the outer `div` an `aside` and the `aside` a `div` in `/apps/web/app/(authenticated)/(app)/app/desktop-sidebar.tsx`? It would be better for a11y. Would love to hear your thoughts.

**Comment by chronark** [comment]
Yeah let's try to be semantically correct.
It's little effort and can help with a11y

**Comment by spiritanand** [comment]
Done @chronark 


LMK if anything else pops up.

**Comment by chronark** [comment]
CleanShot 2023-11-15 at 20 29 56@2x
This is what it looks for me now, that's not ideal :D

we need to hide the scrollbar and truncate the api names I think

**Review by chronark — CHANGES_REQUESTED** [review]
see comment

**Comment by spiritanand** [comment]
@chronark updated. Please LMK if more changes are required.

**Review by perkinsjr — APPROVED** [review]
Looks good.

**Pull request merged**
