### PR TITLE
chore(dashboard/sidebar): improve sidebar overall appearance

### PR DESCRIPTION
**Pull request by guilhermerodz**
Before
app unkey com_apis (1)

After
localhost_3000_apis (1)

### CODE REVIEW

**Comment by guilhermerodz** [comment]
@chronark Mentioned he likes the appearance of the inset main container (offset to bottom, rounded border on top-left)

He also mentioned there may be too many people/company doing this pattern.

@perkinsjr What do you think?

IMO I love it and would ship it.

**Comment by chronark** [comment]
if james has no concerns, I’m good with it. However there are other issues, like the profile button not being sticky anymore

**Comment by perkinsjr** [comment]
The new implementation looks good, as long as we don't regress the fixes ^^ i.e the non sticky which was fixed in a recent PR when the X overflow was fixed

**Comment by guilhermerodz** [comment]
Also fixed the scrolling (sidebar fixed, body flexible)

Before
https://github.com/user-attachments/assets/e01137fc-fb86-49d6-affb-dc206461a2ea

After
https://github.com/user-attachments/assets/16f51b2c-1815-4a02-909f-c87839abc44f

**Comment by chronark** [comment]
lgtm, but I don't understand the symbolism behind the api icon
@guilhermerodz

**Review by chronark — APPROVED** [review]

**Pull request merged**
