### PR TITLE
fix: updated hono npm package readme documentation

### PR DESCRIPTION
**Pull request by emee-dev**
## Type of change
Documentation

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [x] 📖 Refactoring / dependency upgrade / documentation

## Description

I updated the documentation for the hono npm package, by providing the options for the unkey middleware for hono server

### Before this PR

{Please add a screenshot here}
before

### After this PR

{Please add a screenshot here}
after

### CODE REVIEW

**Comment by chronark** [comment]
Can you elaborate what is "fixed" and why you think this is useful?
it looks like it's a lot more verbose, which I'm fine with but then also introduces additional variables that are unused.

**Comment by emee-dev** [comment]
My intention was to add an example for the hono package, I overlooked the unused variables. And the fixed part was mostly my first attempt at doing a PR.

**Comment by chronark** [comment]
Gotcha,

I think a more elaborate examples definitely makes sense, but as a 2nd step, the first example should be minimal

**Comment by emee-dev** [comment]
> Gotcha,
> 
> I think a more elaborate examples definitely makes sense, but as a 2nd step, the first example should be minimal

okay I will update it

**Pull request closed without merging**
