### PR TITLE
feat: show app version

### PR DESCRIPTION
**Pull request by G3root**
## Type of change

- [ ] 🐛 Bug fix
- [x] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation

## Description

shows which version the current production app is running

### After this PR

Screenshot 2023-11-17 at 14-32-59 Open Source API Key Management

### CODE REVIEW

**Comment by chronark** [comment]
Why do you need this?

**Comment by chronark** [comment]
I see
but there's no reason for it to be visible all the time, right?
an api route that returns the version on /_version or similar would solve this issue as well

**Comment by perkinsjr** [comment]
I don't think this brings any value to the application it self.. No one will be using versions outside what is in Prod at any point, we don't have cached instances of old versions thanks to the deployments on Vercel. 

Being an API first project it would make more sense if we returned the version in a header for debugging purposes.

**Comment by G3root** [comment]
> I don't think this brings any value to the application it self.. No one will be using versions outside what is in Prod at any point, we don't have cached instances of old versions thanks to the deployments on Vercel.
> 
self hosters mostly aren't up to date with version in Prod

> Being an API first project it would make more sense if we returned the version in a header for debugging purposes.

agree on this stance 👍🏼 closing this Pr for now.

**Pull request closed without merging**
