### PR TITLE
[oss.gg hackathon] template: fastify + unkey template

### LINKED ISSUE #2378: [oss.gg hackathon] Fastify + Unkey Starter Template
### What side quest or challenge are you solving?

[This template is a starter kit for building APIs using Fastify and Unkey](https://github.com/Vardhaman619/fastify-unkey), designed to facilitate user authentication, rate limiting, and the generation of random facts via the Vercel AI SDK. It provides a structured framework for developers to quickly set up and deploy RESTful APIs with TypeScript support, allowing for efficient development and management of user interactions.

[Check Here](https://github.com/Vardhaman619/fastify-unkey)

### Points

750

### Description

The Fastify + Unkey Starter Kit allows developers to create a fully functional API that incorporates user authentication through the Unkey API, implements rate limiting for controlled usage, and generates random facts using the Vercel AI SDK. The template is structured to use Drizzle ORM with an SQLite database for storing user-generated facts, ensuring data is efficiently handled and queried. It features endpoints for user signup, sign-in, sign-out, and fact management, providing a comprehensive solution for anyone looking to build a fact-based application or service.

### Provide proof that you've completed the task

fastify-ratelimiting-using-unkey

fastify-api-with-unkey-create-key-feature

fastify-api-with-unkey

### PR DESCRIPTION
**Pull request by Vardhaman619**
## What does this PR do?
This PR adds a new starter template using fastify + unkey
#2150 

Closes #2378 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [Contributing Guide](./CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand areas
- [ ] Ran `pnpm build`
- [ ] Ran `pnpm fmt`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Added a new contribution detailing a starter template for Fastify API route protection and rate limiting using Unkey.
  
- **Bug Fixes**
	- Corrected a typo in the description of the Unkey Route protection template.

- **Documentation**
	- Updated the contributions section for clarity and consistency in date formatting.

### CODE REVIEW

**Comment by Vardhaman619** [comment]
@chronark @perkinsjr Could you please take a look at this PR when you get a chance? I'd like to close it soon so I can begin working on other issues.
Let me know if there's anything that needs adjustment.

**Comment by chronark** [comment]
Please add more instructions to your readme. It just tells me how to run it, not how to actually use it?
ie: what routes can I call?

**Comment by Vardhaman619** [comment]
> Please add more instructions to your readme. It just tells me how to run it, not how to actually use it?
> ie: what routes can I call?

Thank you for your feedback! I've updated the README to include detailed instructions on how to use the template, along with information on the available API routes.
[Check out the updated README](https://github.com/Vardhaman619/fastify-unkey)

**Comment by Vardhaman619** [comment]
@chronark Could you please take a look at this PR

**Pull request closed without merging**
