### PR TITLE
fix: Added tailwind solution to fix the the view and copy button missing when key longer than 87 characters. 

### LINKED ISSUE #2401: Copy button not visible if the key is too long
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Reproduction / Replay Link (Optional)

_No response_

### Issue Summary

After creating a key longer than 87 bytes, the copy button is not visible near the key.

### Steps to Reproduce

1. Go to https://app.unkey.com/apis/[api_123]/keys/[ks_123]/new
2. Create a new key with byte size 87 or more.
3. Notice that copy button is not visible 

### Expected behavior

The `copy` and `eye` buttons should be visible regardless of the key size.

### Other information

_No response_

### Screenshots

image

### Version info

```markdown
- OS:
- Node:
- npm:
```

### PR DESCRIPTION
**Pull request by adot-7**
## What does this PR do?

I added **className="overflow-x-auto"** to pre tag in client.tsx to keep the view and copy buttons visible even if the key is longer than 87 characters as before the key was pushing the buttons out and making them inaccessible as a result. 

Fixes #2401

### Before
Screenshot 2024-10-29 194141
### After
Screenshot 2024-10-30 221541

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Go to [https://app.unkey.com/apis/[api_123]/keys/[ks_123]/new](https://app.unkey.com/apis/%5Bapi_123%5D/keys/%5Bks_123%5D/new)
- Create a key of byte size more than 87, for example, 95.
- Notice that both view and copy buttons are visible, which previously they were not. 

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Enhanced the `CreateKey` component for better user experience with a scrollable API key display.
	- Added a new optional field, `refillDay`, to the key management schema for improved refill scheduling.

- **Bug Fixes**
	- Improved the "Create another key" button functionality to reset form fields and refresh the router for a clean state.

- **Documentation**
	- Updated descriptions for API operations to clarify the usage of new and existing parameters.

### CODE REVIEW

**Comment by akash-2004** [comment]
@chronark Hey, I have created this new PR and added a simple tailwind solution as you suggested. Thank you.

**Comment by adot-7** [comment]
@perkinsjr hey would it be possible to merge this PR as hacktoberfest is coming to an end and I have made the necessary changes as suggested by other maintainers.

**Comment by perkinsjr** [comment]
@adot-7 without signing the CLA we can't merge this.

**Comment by adot-7** [comment]
> @adot-7 without signing the CLA we can't merge this.

I have signed it now.

**Comment by adot-7** [comment]
@chronark I have signed the CLA and made the changes necessary.

**Comment by adot-7** [comment]
I have signed the CLA

**Review by chronark — APPROVED** [review]

**Pull request merged**
