### PR TITLE
feat:Retweet and Like Side Quest

### LINKED ISSUE #2326: [🕹️]Retweet and Like Side Quest
### What side quest or challenge are you solving?

Retweet and Like

### Points

50

### Description

I have successfully completed the Retweet and Sidelike quest.

### Provide proof that you've completed the task

https://www.linkedin.com/feed/update/urn:li:activity:7250401710643298305/
image

### PR DESCRIPTION
**Pull request by shindebhavika**
## What does this PR do?
Fixes  #2326
Retweet and Like Side Quest 

[
Screenshot (27)
](url)

I

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [X] Read [Contributing Guide](./CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand areas
- [ ] Ran `pnpm build`
- [ ] Ran `pnpm fmt`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [X] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

## Summary by CodeRabbit

- **Chores**
	- Updated version control settings by changing the tracking status of `.react-email`.
	- Added a comment for clarity in the `.gitignore` file.

### CODE REVIEW

**Comment by chronark** [comment]
why does this change that file?

**Comment by harshsbhat** [comment]
@chronark correct me if I am wrong.

I don't think we have this [side quest for unkey](https://app.campsite.com/unkey/p/notes/unkey-hacktoberfest-side-quests-challenges-lexof2nmtljf).  You probably need to open this on [formbricks side quest](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf)

**Comment by chronark** [comment]
this sidequest needs to go through the formbricks repo, to centralise it.

**Pull request closed without merging**
