### PR TITLE
chore(dashboard/apis): add breadcrumb navigation and improve keys back-forth navigation

### PR DESCRIPTION
**Pull request by guilhermerodz**
Before

https://github.com/user-attachments/assets/eb9bd40d-d464-48d1-a054-7624dff38f00

- Navigation was confusing due to ambiguity, no breadcrumbs or visual hierarchy in any way
- Navigation didn't offer a clear way to get back to the Keys listing
- Key permissions was a whole page by itself

After

https://github.com/user-attachments/assets/e17b29d7-82d4-40f3-9a44-190e5d917455

- Improved navigation by adding breadcrumbs to the whole "APIs" section of the app; that setup/expectation aims to progressively add breadcrumbs to all routes (right now it's only the APIs section)
- Joined a key's "Settings" to its "Permissions" instead of having two different routes; that change was easier to implement rather than keeping them separate, because I didn't want to go for nested tabs, since there is already a tab navigation inside of `/apis/[apiId]**`.

### CODE REVIEW

**Comment by guilhermerodz** [comment]
I'm currently blocked in this PR since the blank/empty page bug is only gone on Next 14.2+ and I cannot find a way to run `pnpm build` without an error related to `nuqs`.

Upgrading to Next 14.2+ solves our bugs, however the build command throws that error related to `nuqs`:

```
> @unkey/dashboard@0.1.30 build /Users/rodz/www/unkey/unkey/apps/dashboard
> next build

  ▲ Next.js 14.2.5
  - Environments: .env
  - Experiments (use with caution):
    · esmExternals

   Creating an optimized production build ...
Failed to compile.

../../node_modules/.pnpm/nuqs@1.17.1_next@14.2.5/node_modules/nuqs/dist/index.js
Attempted import error: 'useRouter' is not exported from 'next/navigation.js' (imported as 'useRouter').

Import trace for requested module:
../../node_modules/.pnpm/nuqs@1.17.1_next@14.2.5/node_modules/nuqs/dist/index.js
./app/(app)/audit/[bucket]/page.tsx
../../node_modules/.pnpm/next@14.2.5_@babel+core@7.24.8_@opentelemetry+api@1.4.1_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2F(app)%2Faudit%2F%5Bbucket%5D%2Fpage&page=%2F(app)%2Faudit%2F%5Bbucket%5D%2Fpage&pagePath=private-next-app-dir%2F(app)%2Faudit%2F%5Bbucket%5D%2Fpage.tsx&appDir=%2FUsers%2Frodz%2Fwww%2Funkey%2Funkey%2Fapps%2Fdashboard%2Fapp&appPaths=%2F(app)%2Faudit%2F%5Bbucket%5D%2Fpage&pageExtensions=tsx&pageExtensions=mdx&pageExtensions=ts&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!./app/(app)/audit/[bucket]/page.tsx?__next_edge_ssr_entry__

../../node_modules/.pnpm/nuqs@1.17.1_next@14.2.5/node_modules/nuqs/dist/index.js
Attempted import error: 'useSearchParams' is not exported from 'next/navigation.js' (imported as 'useSearchParams').

Import trace for requested module:
../../node_modules/.pnpm/nuqs@1.17.1_next@14.2.5/node_modules/nuqs/dist/index.js
./app/(app)/audit/[bucket]/page.tsx
../../node_modules/.pnpm/next@14.2.5_@babel+core@7.24.8_@opentelemetry+api@1.4.1_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2F(app)%2Faudit%2F%5Bbucket%5D%2Fpage&page=%2F(app)%2Faudit%2F%5Bbucket%5D%2Fpage&pagePath=private-next-app-dir%2F(app)%2Faudit%2F%5Bbucket%5D%2Fpage.tsx&appDir=%2FUsers%2Frodz%2Fwww%2Funkey%2Funkey%2Fapps%2Fdashboard%2Fapp&appPaths=%2F(app)%2Faudit%2F%5Bbucket%5D%2Fpage&pageExtensions=tsx&pageExtensions=mdx&pageExtensions=ts&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!./app/(app)/audit/[bucket]/page.tsx?__next_edge_ssr_entry__

../../node_modules/.pnpm/nuqs@1.17.1_next@14.2.5/node_modules/nuqs/dist/index.js
Attempted import error: 'useRouter' is not exported from 'next/navigation.js' (imported as 'useRouter').

Import trace for requested module:
../../node_modules/.pnpm/nuqs@1.17.1_next@14.2.5/node_modules/nuqs/dist/index.js
./app/(app)/audit/[bucket]/page.tsx
../../node_modules/.pnpm/next@14.2.5_@babel+core@7.24.8_@opentelemetry+api@1.4.1_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2F(app)%2Faudit%2F%5Bbucket%5D%2Fpage&page=%2F(app)%2Faudit%2F%5Bbucket%5D%2Fpage&pagePath=private-next-app-dir%2F(app)%2Faudit%2F%5Bbucket%5D%2Fpage.tsx&appDir=%2FUsers%2Frodz%2Fwww%2Funkey%2Funkey%2Fapps%2Fdashboard%2Fapp&appPaths=%2F(app)%2Faudit%2F%5Bbucket%5D%2Fpage&pageExtensions=tsx&pageExtensions=mdx&pageExtensions=ts&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!./app/(app)/audit/[bucket]/page.tsx?__next_edge_ssr_entry__

../../node_modules/.pnpm/nuqs@1.17.1_next@14.2.5/node_modules/nuqs/dist/index.js
Attempted import error: 'useSearchParams' is not exported from 'next/navigation.js' (imported as 'useSearchParams').

Import trace for requested module:
../../node_modules/.pnpm/nuqs@1.17.1_next@14.2.5/node_modules/nuqs/dist/index.js
./app/(app)/audit/[bucket]/page.tsx
../../node_modules/.pnpm/next@14.2.5_@babel+core@7.24.8_@opentelemetry+api@1.4.1_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2F(app)%2Faudit%2F%5Bbucket%5D%2Fpage&page=%2F(app)%2Faudit%2F%5Bbucket%5D%2Fpage&pagePath=private-next-app-dir%2F(app)%2Faudit%2F%5Bbucket%5D%2Fpage.tsx&appDir=%2FUsers%2Frodz%2Fwww%2Funkey%2Funkey%2Fapps%2Fdashboard%2Fapp&appPaths=%2F(app)%2Faudit%2F%5Bbucket%5D%2Fpage&pageExtensions=tsx&pageExtensions=mdx&pageExtensions=ts&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!./app/(app)/audit/[bucket]/page.tsx?__next_edge_ssr_entry__


> Build failed because of webpack errors
/Users/rodz/www/unkey/unkey/apps/dashboard:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @unkey/dashboard@0.1.30 build: `next build`
Exit status 1
```

**Comment by chronark** [comment]
@guilhermerodz gotcha, thanks for the update.

I guess we need to upgrade anyways, we've just been postponing it cause there was no immediate need.

Let's try to upgrade in a separate PR and then come back here

**Comment by chronark** [comment]
CleanShot 2024-07-29 at 19 24 22@2x
It doesn't really look like breadcrumbs when there's a single element

**Comment by chronark** [comment]
I'm looking at ratelimits, yet I see these breadcrumbs
CleanShot 2024-07-29 at 19 25 58@2x

**Review by chronark — CHANGES_REQUESTED** [review]
Disable breadcrumbs on non api pages, or show the correct ones

**Comment by guilhermerodz** [comment]
@chronark can you check if you still have layout shift?

**Comment by chronark** [comment]
lgtm

**Review by chronark — APPROVED** [review]

**Review by chronark — APPROVED** [review]

**Pull request merged**
