### PR TITLE
feat: Add profile on mobile top nav

### LINKED ISSUE #2207: Feature/Add profile on mobile top nav
### Preliminary Checks

- [X] I have reviewed https://unkey.com/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Is your feature request related to a problem? Please describe.

The feature of the Profile seems to be on the desktop but there is no profile on mobile so I want to create a feature request for this.

### Describe the solution

Solves the User experience for Mobile users who can see their profile, update details, and so on. 

### Describe alternatives you have considered (if any)

I have added an image in additional context to understand graphically.

### Additional context

image

### PR DESCRIPTION
**Pull request by pragyananda**
## What does this PR do?

This PR adds a feature on the mobile top side adds a profile component that can be useful for users.

Fixes #2207 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Introduced a `UserButton` component in the sidebar for user-specific actions.

- **Improvements**
	- Enhanced the `MobileSideBar` for better responsiveness with flexible width adjustments.
	- Updated the `UserButton` for improved layout and visibility on different screen sizes, including adjustments to avatar size and dropdown positioning.
	- Minor updates to the `Feedback` component for standardized error message formatting.

These changes collectively enhance the user experience by providing a more adaptable and functional interface.

### CODE REVIEW

**Comment by chronark** [comment]
Please sign the CLA and fix the conflict

**Comment by pragyananda** [comment]
i think done.

**Review by chronark — CHANGES_REQUESTED** [review]
On some breakpoints, the user button is not right aligned
CleanShot 2024-10-08 at 15 34 58@2x

It should probably be in the top right corner, no?

**Comment by pragyananda** [comment]
yeah wait i'll check

**Comment by pragyananda** [comment]
hii @chronark i checked and i solved this can you check please.

**Comment by chronark** [comment]
Should we display the name if there's enough space?
CleanShot 2024-10-09 at 12 58 29@2x

**Comment by pragyananda** [comment]
ya as you wish .

**Comment by pragyananda** [comment]
@chronark added.

**Comment by chronark** [comment]
CleanShot 2024-10-09 at 17 59 22@2x
don't you think it would look better with the name on the left and without the chevron?

**Comment by pragyananda** [comment]
@chronark done.

**Review by chronark — APPROVED** [review]

**Review by chronark — APPROVED** [review]

**Pull request merged**
