### PR TITLE
feat: Koa.js RBAC middleware with Unkey

### PR DESCRIPTION
**Pull request by harshsbhat**
Adds a template to showcase the implementation of RBAC middleware using the Koa.js and Unkey.

https://github.com/harshsbhat/unkey-koa

Fixes https://github.com/unkeyed/unkey/issues/2150

## Summary by CodeRabbit

- **New Features**
	- Added a new template entry for using Unkey with the Koa.js framework, including a link to the Koa.js RBAC route protection repository.

### CODE REVIEW

**Comment by chronark** [comment]
can you add the required root key permissions in your link in the readme?
like so:
`https://app.unkey.com/settings/root-keys/new?permissions=api.*.create_api,another..`

**Comment by harshsbhat** [comment]
> can you add the required root key permissions in your link in the readme? like so: `https://app.unkey.com/settings/root-keys/new?permissions=api.*.create_api,another..`

Oh yeah. this feature was introduced recently right?

**Comment by harshsbhat** [comment]
Done. For all other templates too

**Pull request closed without merging**
