### PR TITLE
chore(dashboard/container): center and set maximum width

### PR DESCRIPTION
**Pull request by guilhermerodz**
Before
CleanShot 2024-07-26 at 05 45 33@2x

After
CleanShot 2024-07-26 at 05 45 31@2x

### CODE REVIEW

**Comment by chronark** [comment]
This feels a bit aggressive, here's my 14" mbp for reference:


CleanShot 2024-07-26 at 11 10 36@2x


1280px would be better I think, which maps to tailwind's `xl`

**Review by chronark — CHANGES_REQUESTED** [review]
see comment

**Comment by chronark** [comment]
The linting is failing, I believe this is my fault but I'm unsure how I got it past CI in the first place
can you run `pnpm fmt` please and commit the changes

**Comment by guilhermerodz** [comment]
> This feels a bit aggressive, here's my 14" mbp for reference:
> 
> CleanShot 2024-07-26 at 11 10 36@2x
> 
> 1280px would be better I think, which maps to tailwind's `xl`

I believe 1280px is too much, 1150px is what I see at maximum in most apps

**Comment by perkinsjr** [comment]
/settings/billing the card no longer looks like a card and is squashed on a MBP 14 

Before:
image


After:

image

**Comment by chronark** [comment]
wdym doesn't look like a card?
it has a border and everything

**Comment by chronark** [comment]
> > This feels a bit aggressive, here's my 14" mbp for reference:
> > CleanShot 2024-07-26 at 11 10 36@2x
> > 1280px would be better I think, which maps to tailwind's `xl`
> 
> I believe 1280px is too much, 1150px is what I see at maximum in most apps

who's using that?
of that's popular, I'm happy to follow that

**Comment by perkinsjr** [comment]
As I stated It's completely squashed, which makes the card design just look like a rounded square. If you look at the before and then the after.

I'm not willing to ship something where the design regresses and looks worse.

We should reduce the size of the bars on the left to make room for the card or decide how to fix this before shipping.

**Comment by chronark** [comment]
I don't think it looks that bad, but agree the card is too full and the bullet points need to be reworked anyways cause they're flat out wrong
I put it there initially to fill the void and would be fine with removing the bullet points now

**Comment by chronark** [comment]
oh wait, are you talking about the credit card or the `<Card/>`?

agreed, the credit card is a bit tall now

**Comment by perkinsjr** [comment]
The credit card yeah it needs aspect ratio or something to stop it being pushed up.

**Comment by chronark** [comment]
10/10 communication 😄
agreed though @guilhermerodz could you take a look at it?
I might have just set a fixed height on it

**Comment by guilhermerodz** [comment]
Now at 1152px

Before (1024px):
CleanShot 2024-07-26 at 16 10 48@2x


After (1152px):
CleanShot 2024-07-26 at 16 09 16@2x

**Comment by chronark** [comment]
what about the credit card’s aspect ratio??

**Comment by perkinsjr** [comment]
I still think we have way to much whitespace it's almost 1/3 product and 2/3 whitespace. 

I don't understand the reason to have so much whitespace on a larger screen (this is only 24inch monitor) for the image below? 

image

**Comment by guilhermerodz** [comment]
> what about the credit card’s aspect ratio??

Same as prod now

CleanShot 2024-07-26 at 16 19 02@2x

**Comment by chronark** [comment]
cause it looks bad on large screens
I’m with rodz on this one
[CleanShot 2024-07-26 at 21.24.01.png](https://files.slack.com/files-pri/T05T2KX8C3X-F07ECAT8GLC/cleanshot_2024-07-26_at_21.24.01.png)

**Comment by chronark** [comment]
we didn’t lose any information by narrowing it down

**Comment by chronark** [comment]
because we’re not actively utilizing the larger space, it’s just stretched out

**Comment by perkinsjr** [comment]
It looks terrible. 

It looks like we've coded for a tablet and then left it alone. There has to be a happy medium between entire layout and 2/3s whitespace for the average user.

**Comment by guilhermerodz** [comment]
I don’t think there’s too much whitespace, and even if there was extra whitespace, that wouldn’t couldn’t be worse than the current one
[CleanShot 2024-07-26 at 16.25.22@2x.png](https://files.slack.com/files-pri/T05T2KX8C3X-F07E9NUTA4B/cleanshot_2024-07-26_at_16.25.22_2x.png)
[CleanShot 2024-07-26 at 16.25.20@2x.png](https://files.slack.com/files-pri/T05T2KX8C3X-F07ECAZ7L20/cleanshot_2024-07-26_at_16.25.20_2x.png)

**Comment by guilhermerodz** [comment]
(I’m scaling down .67% on that screenshot)

**Comment by guilhermerodz** [comment]
I can still make it 1280px large tho

**Comment by chronark** [comment]
do these all look terrible to you?
[CleanShot 2024-07-26 at 21.26.36.png](https://files.slack.com/files-pri/T05T2KX8C3X-F07ECB3N9GC/cleanshot_2024-07-26_at_21.26.36.png)
[CleanShot 2024-07-26 at 21.26.53.png](https://files.slack.com/files-pri/T05T2KX8C3X-F07E9P15LAX/cleanshot_2024-07-26_at_21.26.53.png)
[CleanShot 2024-07-26 at 21.27.03.png](https://files.slack.com/files-pri/T05T2KX8C3X-F07E9SATTB4/cleanshot_2024-07-26_at_21.27.03.png)

**Comment by guilhermerodz** [comment]
Current one is 1152px

**Comment by guilhermerodz** [comment]
Filling all the screen with information is also not good

**Comment by chronark** [comment]
personally I like it if the content is not all over the screen, cause I don’t have to play tennis with the mouse as much

but that’s just my preference, we should find a middle ground

**Comment by guilhermerodz** [comment]
yea initially that was bothering me… not only the visual, but it requires a lot of mouse movement to reach each part of the main section

**Comment by perkinsjr** [comment]
If you are all happy with it go for it. I just think it's so extreme to go from a full screen to well lets just fill the smallest part of the screen with data in the center and 2/3rds be white space. With a sidebar.

I totally think that our website on a full larger screen also has the same issue which I raised  when we made the changes and conceded on.

**Comment by chronark** [comment]
I would agree if using the full screen would actually show more data, but all it does is stretch it out, cause we don’t have such large breakpoints to make use of it

**Comment by guilhermerodz** [comment]
We can still make it larger afterwards by increasing container width and adding more columns to a grid-like screen (example /apis showing 4 to 5 columns instead of just 3 could help a bit)

However it’s sooo challenging to go full-width like 100vw like Linear is doing, because there should be enough content and well designed content for the main section.

**Comment by chronark** [comment]
for example axiom uses the full width and it is way worse imo, cause now the information is at the left and the right side of the screen and I have to go back and forth
[CleanShot 2024-07-26 at 21.34.57.png](https://files.slack.com/files-pri/T05T2KX8C3X-F07ENHPKYN5/cleanshot_2024-07-26_at_21.34.57.png)

**Review by chronark — APPROVED** [review]

**Pull request merged**
