### PR TITLE
fix: show long permission names with ellipses and full text on hover

### LINKED ISSUE #1885: long permission names are cut off
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Reproduction / Replay Link (Optional)

_No response_

### Issue Summary

When using long permission names they get cutoff 

image

### Steps to Reproduce

1. Use a long permission name for example api.account.v1.AccountService.DeleteConnections
2. See that they get cut off in the dashboard

### Expected behavior

If the permission name is too long we should make an on hover with ellipsis 

### Other information

_No response_

### Screenshots

_No response_

### Version info

```markdown
N/A
```

### PR DESCRIPTION
**Pull request by DeepaPrasanna**
## What does this PR do?

Fixes #1885 

Attached video: 
https://www.loom.com/share/7f3a5848d86f4bbf9f2f4e8ef1a41294?sid=424b1b28-c69e-449d-b588-7c6cece49cd8

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Use long permission names for example   api.account.v1.AccountService.Accounts.DeleteConnections
- Text should be truncated with an ellipsis and should show full text on hover

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand areas
- [ ] Ran `pnpm build`
- [ ] Ran `pnpm fmt`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

### CODE REVIEW

**Review by perkinsjr — CHANGES_REQUESTED** [review]
This fixes it for roles but not permissions. 

Permissions are still overflowing and or broken with extra long names

**Comment by DeepaPrasanna** [comment]
did u mean here?
Screenshot 2024-07-13 223117

**Comment by perkinsjr** [comment]
> did u mean here?
> 
> Screenshot 2024-07-13 223117
> 
> Untitled
> 
> 
> 
> 

Yes, that's our permissions section. As well as if you click into a permission to see the title and the name will span the entirety.

**Comment by DeepaPrasanna** [comment]
are the following changes okay?

Screenshot 2024-07-16 224851
Screenshot 2024-07-16 232029
Screenshot 2024-07-16 232040
Screenshot 2024-07-16 232053
image

**Comment by perkinsjr** [comment]
@guilhermerodz can you take a look at this and decide how you want the dashboard to proceed.

**Comment by perkinsjr** [comment]
cc **Guilherme Rodz** tagged you in this issue can you take a look, see how you feel about the changes.

**Review by guilhermerodz — DISMISSED** [review]
Truncating with ellipses (three dots) is a great workaround for this.

There are still some alignment issues, such as title + description you showed on image 5 but that's not related to the truncated long names at all. Great job!

**Review by guilhermerodz — CHANGES_REQUESTED** [review]
Just missing a `truncate` className on the description of it
CleanShot 2024-07-18 at 16 05 45@2x
Add `truncate` and there you go
CleanShot 2024-07-18 at 16 05 36@2x

**Comment by DeepaPrasanna** [comment]
I added here too 
image

**Review by guilhermerodz — APPROVED** [review]

**Review by perkinsjr — APPROVED** [review]

**Pull request merged**
