### PR TITLE
fix: member role shouldn't be able to change others role

### PR DESCRIPTION
**Pull request by bipulpoudel**
## Type of change

- [x] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation

## Description

User with role "Member" shouldn't be able to change other user's role in Settings->Team page.

### Before this PR

User with role "Member" could change other's role:

image

### After this PR

Fixed now:

image

### Related Issue (optional)

https://github.com/unkeyed/unkey/issues/549

### CODE REVIEW

**Comment by bipulpoudel** [comment]
I have also hide, Members/Invitations switcher from user with "Member" role.

**Review by perkinsjr — APPROVED** [review]

**Review by chronark — APPROVED** [review]

**Comment by chronark** [comment]
nice one, thanks

**Comment by chronark** [comment]
@bipulpoudel can you please signt he CLA, then we can merge

> [CLA assistant check](https://cla-assistant.io/unkeyed/unkey?pullRequest=550) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/unkeyed/unkey?pullRequest=550) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/unkeyed/unkey?pullRequest=550) it.

**Comment by bipulpoudel** [comment]
@chronark , done :)

**Pull request merged**
