### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by domeccleston**
## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [x] 📖 Refactoring / dependency upgrade / documentation

## Description

Small tweaks to the CONTRIBUTING guide to (a) add one missing dependency I didn't have installed (Go) and (b) clarify that the logs of pnpm bootstrap contain the remaining environment variables (I thought the script updated the .env file automatically, missed the terminal output, and ended up having to run the script again 😄)

### CODE REVIEW

**Comment by perkinsjr** [comment]
Hey Dom 👋

Can you also update the documentations in apps/docs/contributing/getting-started

We have it in two places.

**Review by perkinsjr — CHANGES_REQUESTED** [review]
see my note

**Comment by chronark** [comment]
oh snap, I forgot we had this file too
should we consolidate everything into apps/docs/contributing/getting-started?

**Comment by domeccleston** [comment]
Thanks @chronark @perkinsjr! @chronark saw you already updated this in the docs [here](https://github.com/unkeyed/unkey/commit/1de87d7f7783eaf2aff93896ef0bf69bc47eaaf3) – do you want to merge this and keep it in Github, or close it and link to the docs instead?

**Comment by chronark** [comment]
Yeah sorry, that's my bad.
I've stripped down the CONTRIBUTING.md already to just link to the docs after more people ran into issues by following the wrong instructions.

Closing this one, can you create a new PR with improvements to ` apps/docs/contributing/getting-started` if necessary?

Thank you

**Pull request closed without merging**
