### PR TITLE
fix: handled form using useEffect hook

### PR DESCRIPTION
**Pull request by ankurjaiswalofficial**
## What does this PR do?

Updated the delete-api file where i added the useEffect to handle mounting and unmounting of the delete api dialog .

Fixes #2316 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

How should this be tested?
Navigate to Dashboard => API's workspace => Select an API => Go to API Settings => Click on Delete API.
Open the Delete API dialog, enter data in the input fields, close the dialog, and then reopen it.
Verify that the input fields are reset to their default (empty) state on reopening.

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Enhanced the Delete API dialog to reset form fields and clear errors upon closing.

- **Bug Fixes**
	- Corrected a minor class name issue in the Card component for improved styling.

### CODE REVIEW

**Comment by perkinsjr** [comment]
@ankurjaiswalofficial please sign the CLA

**Comment by ankurjaiswalofficial** [comment]
> @ankurjaiswalofficial please sign the CLA

Ya, I signed it now

**Comment by chronark** [comment]
This PR is incorrectly referencing another PR, not an issue.
Regardless, the issue is currently assigned to someone else, please do not do any work unless you are assigned because we may have to reject it

**Comment by ankurjaiswalofficial** [comment]
what's this you people are tricking here this branch was assigned to me and i was asked to sign the CLA, 
you assigned the branch to yourself this is ridiculous...

**Pull request closed without merging**
