### PR TITLE
feat: create/delete/get/list for permissions and roles

### PR DESCRIPTION
**Pull request by chronark**

### CODE REVIEW

**Comment by perkinsjr** [comment]
you don’t need to tag me it’s automatic

**Comment by chronark** [comment]
but I want to

**Comment by perkinsjr** [comment]
well every time you do you are adding to my notifications 🤣

**Comment by chronark** [comment]
how so?
it didn’t work

**Comment by perkinsjr** [comment]
[image.png](https://files.slack.com/files-pri/T05T2KX8C3X-F07BH1SJK7V/image.png)

**Comment by chronark** [comment]
yes I got that

**Comment by perkinsjr** [comment]
So now everytime you write something here it pings me.

**Comment by chronark** [comment]
oooh

**Comment by chronark** [comment]
ok, so this actually also syncs all thread replies to github… that’s an easy leak

**Comment by perkinsjr** [comment]
Yes I was just typing that 🙃

**Pull request merged**
