### PR TITLE
chore: added navigation if no keys on page

### PR DESCRIPTION
**Pull request by MichaelUnkey**
## What does this PR do?

eng-1049
Fixes # (issue)

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

* [ ] Bug fix (non-breaking change which fixes an issue)
* [x] Chore (refactoring code, technical debt, workflow improvements)
* [ ] Enhancement (small improvements)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

## How should this be tested?

Verify create key and back buttons function

### Required

* [x] Filled out the "How to test" section in this PR
* [x] Read [Contributing Guide](./CONTRIBUTING.md)
* [x] Self-reviewed my own code
* [x] Commented on my code in hard-to-understand areas
* [x] Ran `pnpm build`
* [x] Ran `pnpm fmt`
* [x] Checked for warnings, there are none
* [x] Removed all `console.logs`
* [x] Merged the latest changes from main onto my branch with `git pull origin main`
* [x] My changes don't cause any responsiveness issues

### Appreciated

* [ ] If a UI change was made: Added a screen recording or screenshots to this PR
* [ ] Updated the Unkey Docs if changes were necessary

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjgyZDZlMzJhNmFiOWVlZjU1OWE1Y2QiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.N8XLk4GN5yHbjeKW90hl8CpDMAbrQLqqnVZKC6tw24A">Huly&reg;: <b>ENG-1831</b></a></sub>

### CODE REVIEW

**Comment by chronark** [comment]
CleanShot 2024-07-03 at 18 20 33@2x
Can you please horizontally align the buttons, this doesn't look good.

**Review by chronark — CHANGES_REQUESTED** [review]
See screenshot in comments and I think the priorities are not indicated correctly
"Create Key" should be primary
"Back" should be secondary

**Comment by chronark** [comment]
CleanShot 2024-07-05 at 10 56 03@2x
buttons are still the wrong colors

**Comment by MichaelUnkey** [comment]
Not sure if this is the correct way to change the button colors?

**Review by perkinsjr — CHANGES_REQUESTED** [review]
Please fix the error on the build. Type error: Property 'variant' is missing in type '{ keyAuthId: string; }' but required in type '{ keyAuthId: string; variant: Variant; }'.

**Review by perkinsjr — APPROVED** [review]

**Review by perkinsjr — APPROVED** [review]

**Comment by perkinsjr** [comment]
I did this.. because GH was stuck even though I approved the changes already.

**Comment by MichaelUnkey** [comment]
saw that

**Pull request merged**
