### PR TITLE
fix :cleanup timeout

### PR DESCRIPTION
**Pull request by G3root**
## Type of change

- [x] 🐛 Bug fix

## Description

cleanup of setTimeout is not handled, which sometimes glitches when the button is pressed continuously. this PR aims to fix that

### CODE REVIEW

**Comment by chronark** [comment]
Could you elaborate how this "glitch" manifests?
I couldn't find a problem when clicking it

**Comment by G3root** [comment]
> Could you elaborate how this "glitch" manifests? I couldn't find a problem when clicking it

here's the reproduction of the issue, as you can see the key isn't visible for 10 seconds which it should be.

[Screencast 2023-11-17 07:22:30.webm](https://github.com/unkeyed/unkey/assets/84864519/2558c25b-fc31-4968-8881-09d33a6e83ee)

**Comment by chronark** [comment]
Hmm, I can not reproduce this at all, even when spamming the button
why could that be different on your end?

**Comment by G3root** [comment]
> Hmm, I can not reproduce this at all, even when spamming the button why could that be different on your end?

weird though, i can still reproduce this in my pixel 7 🤔

**Comment by perkinsjr** [comment]
I also tried on 3 devices 

- Mac 
- Windows
- iPhone 

All work as intended.

**Comment by G3root** [comment]
The problem with the current useEffect is that setTimeout runs both when `isVisible` is true and false, but it should only run when `isVisible` is true. Additionally, there is no cleanup function to remove the setTimeout call while the component unmounts and the setTimeout is still running.

**Comment by perkinsjr** [comment]
Decided on closing this for now. 

Tried recreating it a number of different ways and even with the video. I cannot recreate it, if this occurs again we will have to dig deeper once again.

**Pull request closed without merging**
