### PR TITLE
refactor: expiration iso text input to datepicker

### PR DESCRIPTION
**Pull request by bipulpoudel**
## Type of change

- [x] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation

## Description

Add date picker to expiration date for key settings.

### Before this PR

image

### After this PR

image

### Related Issue (optional)

https://github.com/unkeyed/unkey/issues/515

### CODE REVIEW

**Comment by bipulpoudel** [comment]
I have also removed unused import in carrers page, which was causing issue in pnpm run fmt command :)

**Comment by chronark** [comment]
CleanShot 2023-11-18 at 23 32 16

Looks like there's a bug with the timezone or locality, cause when I save the same time, it goes back 1 hour for me

**Comment by al3rez** [comment]
```
  defaultValue={
    apiKey.expires
      ? new Date(new Date(apiKey.expires).getTime() - (new Date(apiKey.expires).getTimezoneOffset() * 60000)).toISOString().slice(0, -1)
      : ""
  }
```

By taking away the time zone difference from the original time, we basically tweak the date and time to match your local time zone. This should help sort out the problem where the time seems to jump back by an hour.

@chronark @bipulpoudel

**Comment by bipulpoudel** [comment]
@al3rez , are you facing this issue? in your local code? Unfortunately, I am not facing this issue. 

I have tried to push the code for the fix, it does include formatting, which should have fixed this.

If, this doesn't fix it, I will try to push your code :)

**Comment by bipulpoudel** [comment]
@chronark , would you be able to check, if this fix works?

I cannot test on my device :(

**Comment by perkinsjr** [comment]
I can check today.

**Comment by bipulpoudel** [comment]
Thanks @perkinsjr  :)

**Comment by perkinsjr** [comment]
So the code does function when deployed.

Couple things I've found so far.

1. Dates prior to today, error but not indication of why. 
2. When selecting today the time needs to be in the future to be valid however I had to increase the time by 3 minutes or so before it wouldn't error again. 

In the UI it makes sense to only allow dates from today + a few minutes and future because we offer the ability to disable it.

**Review by perkinsjr — CHANGES_REQUESTED** [review]
See my note

**Comment by perkinsjr** [comment]
@bipulpoudel just checking in. If you are continuing work on this?

**Comment by perkinsjr** [comment]
Closing this PR it's 30 days old.

**Pull request closed without merging**
