### PR TITLE
fix: Adds icons to Details in Api key page and root api key page.

### LINKED ISSUE #752: Add icon for details button
### Preliminary Checks

- [X] I have reviewed https://unkey.dev/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Is your feature request related to a problem? Please describe.

The current menu for details and Revoke keys looks like revoke keys is a submenu of details 
Screenshot (15)

### Describe the solution

Adding an icon for details button 
Before:
Screenshot (15)
After:
Group 36

### Describe alternatives you have considered (if any)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ErrolFernandes**
## What does this PR do?

Fixes #752 

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand areas
- [ ] Ran `pnpm build`
- [ ] Ran `pnpm fmt`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

### CODE REVIEW

**Comment by perkinsjr** [comment]
@ErrolFernandes please run 

`pnpm fmt`

**Review by perkinsjr — CHANGES_REQUESTED** [review]
please run `pnpm fmt`

**Comment by ErrolFernandes** [comment]
`pnpm fmt`

**Review by perkinsjr — CHANGES_REQUESTED** [review]
Icon overflows to the next line when selecting details (API key page and root key page), see below.

image

**Pull request closed without merging**
