### PR TITLE
chore: add Unkey + Flutter coupon code generator template [SIDE QUEST]

### PR DESCRIPTION
**Pull request by unrenamed**
## What does this PR do?

Adds a template that showcases a Flutter app that integrates the Unkey API to generate and validate coupon codes for a coffee shop, providing a secure and seamless checkout experience.

[Repository](https://github.com/unrenamed/unkey-coffee-shop) | [Demo video](https://drive.google.com/file/d/1ag_lVzGXOpDIvQD7YvOKISVfMhtYET0K/view?usp=sharing) | [Screenshots](https://github.com/unrenamed/unkey-coffee-shop?tab=readme-ov-file#screenshots)

Fixes #2150

## Summary by CodeRabbit

- **New Features**
	- Added a new project entry titled "Coffee Shop Coupon Code Generator" to the showcase list for Unkey, including a link to the GitHub repository.

### CODE REVIEW

**Comment by harshsbhat** [comment]
Damn!! Looks goooodd!! 🔥💯

**Comment by harshsbhat** [comment]
Damn!! Looks goooodd!! 🔥💯

**Comment by unrenamed** [comment]
> Damn!! Looks goooodd!! 🔥💯

Ha-ha 😄  Thank you. Flutter is 🔥  for developing mobile apps at short notice

**Pull request closed without merging**
