### PR TITLE
oss.gg: side quest blog side quest 8, follow the unkey x, starry eyed supporter, create a template [3200 points]

### PR DESCRIPTION
**Pull request by Yash-1511**
###  Description
Completed the challenge of side quest Follow on X, created a template that uses unkey api to protect and gathering five friends to star the repository.

- Adds a Unkey Hapi.js boilerplate for route protection[750 Points]

https://github.com/Yash-1511/hapi-unkey-template

- Adds Deno + Hono middleware for unkey[750 Points]

https://github.com/Yash-1511/hono-unkey-deno

## Write a blog about unkey api that i use in our application [1500 points]

https://medium.com/@yashp3020/how-i-secured-my-ai-powered-legal-compliance-api-with-unkey-a9df815209b2

### follow on X screenshot[50 points]

WhatsApp Image 2024-10-13 at 18 43 09

### GitHub Usernames of Friends [150 Points]
1. [@virugamacoder](https://github.com/virugamacoder)
2. [@harshp421](https://github.com/harshp421)
3. [@Felixcoder308](https://github.com/Felixcoder308)
4. [@nandani-1411](https://github.com/nandani-1411)
5. [@gtlYashParmar](https://github.com/gtlYashParmar)

### Screenshots

1. [@virugamacoder](https://github.com/virugamacoder)
virugam

2. [@harshp421](https://github.com/harshp421)
harsh

3. [@Felixcoder308](https://github.com/Felixcoder308)
parth

4. [@nandani-1411](https://github.com/nandani-1411)
nandani

5. [@gtlYashParmar](https://github.com/gtlYashParmar)
yash

## Summary by CodeRabbit

- **New Features**
	- Added a new participant, Yash Parmar, to the "Follow the Unkey X account" side quest.
	- Introduced new template submissions for using Unkey with Hapi.js and Hono frameworks.
	- Updated the "Use Unkey" document to include a new side quest entry.

- **Updates**
	- Updated contribution details in the "Starry-eyed Supporter" document, reflecting the latest participant and date.
	- Revised the date in the "Starry-eyed Supporter" document to reflect the latest contribution.
	- Added a new entry for "Starry-eyed Supporter" with Zia Ur Rehman and a link to a GitHub issue.
	- Updated the "Use Unkey" document with a new entry and revised date.

### CODE REVIEW

**Comment by Yash-1511** [comment]
> @Yash-1511 could you update your template to use the new way of checking keys
> 
> https://github.com/Yash-1511/hapi-unkey-template/blob/c1fbd1a6b9773df1d736cac660f8e45b8098a69e/server.js#L48 you should pass in the apiID too
> 
> ```ts
> const { result, error } = await verifyKey({ key: "key_123", apiId: "api_123" });
> ```

Hey, I have updated this.

**Comment by chronark** [comment]
It looks like https://github.com/FelixCoder308 was created just to star the oss.gg repositories, that's against the rules

**Comment by Yash-1511** [comment]
> It looks like https://github.com/FelixCoder308 was created just to star the oss.gg repositories, that's against the rules
Actually, the account wasn't created just for starring those repositories. My friend started freelancing around 3-4 months ago, which is when they created this GitHub account. While there may not be many public repositories, there are some private ones. You can verify this by checking the API at the link provided:
 https://api.github.com/users/FelixCoder308.

Also, could you please share the rulebook or guidelines you're referring to? I'd like to review the specific rules you're mentioning.

**Pull request closed without merging**
