### PR TITLE
fix: bug#2432 Filter options sorted alphabetically

### LINKED ISSUE #2432: /templates filters should be ordered alphabetically
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Reproduction / Replay Link (Optional)

_No response_

### Issue Summary

The filter options right now are in no particular order.

### Steps to Reproduce

1. go to https://unkey.com/templates
2. look at the filters on the left

### Expected behavior

Filter options should be sorted alphabetically

### Other information

_No response_

### Screenshots

CleanShot 2024-10-15 at 10 21 36@2x

### Version info

```markdown
/
```

### PR DESCRIPTION
**Pull request by Arslan-Muhammad**
## What does this PR do?

This PR will fix Filter options and sorted them alphabetically.

Fixes #2432

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

No need of any test just test by locally run project 

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [ ] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
image

- [ ] Updated the Unkey Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Introduced alphabetical sorting for displayed languages and frameworks, enhancing user experience.

### CODE REVIEW

**Comment by chronark** [comment]
please sign the CLA

**Comment by Arslan-Muhammad** [comment]
Please approve this PR or type any suggestion regarding PR.

**Comment by chronark** [comment]
this only works for frameworks, not languages

**Comment by Arslan-Muhammad** [comment]
> this only works for frameworks, not languages

@chronark 
Please check, now working for both frameworks and languages.

**Pull request merged**
