### PR TITLE
docs: integrated unkey's ratelimiter into my project and wrote a blog post on the same

### LINKED ISSUE #2346: [oss.gg hackathon]
### What side quest or challenge are you solving?

Use Unkey in your app and write a blog post about it.

### Points

1500

### Description

Integrated Unkey's ratelimiter into my latest project [CodeStash](https://codestash.baghel.dev/) to ratelimit an AI feature.

And then wrote an extensive technical blog on dev.to about the same.

### Provide proof that you've completed the task

[Link to the blog](https://dev.to/devanshbaghel/enhancing-codestash-with-unkeys-ratelimiter-4d8c)

[Link to the AI feature/ratelimited route](https://codestash.baghel.dev/post/66f18c3e1fbd570b39e6a223), Click the "Explain this" button more than 10 times in 60 seconds to get ratelimited.

Screenshot of the blog:

### PR DESCRIPTION
**Pull request by Devansh-Baghel**
## What does this PR do?
Integrated Unkey's ratelimiter into my latest project [CodeStash](https://codestash.baghel.dev/) to ratelimit an AI feature.

And then wrote an extensive technical blog on dev.to about the same.

Fixes #2346 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

[Link to the blog post](https://dev.to/devanshbaghel/enhancing-codestash-with-unkeys-ratelimiter-4d8c)

[Link to the AI feature/ratelimited route](https://codestash.baghel.dev/post/66f18c3e1fbd570b39e6a223), Click the "Explain this" button more than 10 times in 60 seconds to get ratelimited.

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Introduced a new side quest for creating a template to build an API protected by Unkey.
	- Added a side quest encouraging users to integrate Unkey into their app and document the process in a blog post.
- **Updates**
	- Updated requirements and points system for the new side quests.
	- Added recent contributions section with new entries, including a starter template by Devansh Baghel.
	- Updated blog post entry with new date and author information.

### CODE REVIEW

**Comment by perkinsjr** [comment]
Hi @Devansh-Baghel can you point out where this is in your project?

I don't see Unkey integrated in the main branch and no mention of it in the stack. 

It looks like you made a template which is separate from the actual repository.

**Comment by Devansh-Baghel** [comment]
Hi @perkinsjr sorry the latest commit wasn't pushed yet. 

[Here](https://github.com/Devansh-Baghel/CodeStash/commit/c5562944f23b95cb26fcec83aea97416c7200a6e) is the commit in the main branch that adds this, also added in the [readme](https://github.com/Devansh-Baghel/CodeStash/blob/main/README.md#backend) of the project.

The template repo that i created was for a separate oss.gg submission which i have now gotten the points awarded for. ([issue](https://github.com/unkeyed/unkey/issues/2306), [pr](https://github.com/unkeyed/unkey/pull/2308)) but the pr for that is still open.

**Comment by Devansh-Baghel** [comment]
Hey @chronark

Hi, is there anything else I should do or notify someone for this pr?

**Comment by chronark** [comment]
@Devansh-Baghel james will get to it when he's available

**Pull request merged**
