### PR TITLE
feat: follow unkey on X #2323

### PR DESCRIPTION
**Pull request by siddhakdak**
followed successfully

## What does this PR do?
Fixes # 2323

## Type of change
oss.gg side quest challenge: Follow the Unkey X account

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [X ] Read [Contributing Guide](./CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand areas
- [ ] Ran `pnpm build`
- [ ] Ran `pnpm fmt`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

Screenshot 2024-10-11 at 3 55 10 PM

## Summary by CodeRabbit

- **New Features**
	- Added a new entry for user Siddhak dak, including their X account handle and link for the side quest participation.
  
- **Documentation**
	- Updated the document to reflect the new entry while maintaining the existing format for previous participants.

### CODE REVIEW

**Comment by siddhakdak** [comment]
followed successfully

**Comment by chronark** [comment]
you need to sign the CLA please

**Comment by chronark** [comment]
@siddhakdak please sign the CLA and resolve the merge conflicts

**Pull request closed without merging**
