### PR TITLE
fix: Workspace Permissions overlaps with their descriptions on smaller windows

### LINKED ISSUE #2125: [VISUAL/UI] Workspace Permissions overlaps with their descriptions on smaller windows
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Reproduction / Replay Link (Optional)

_No response_

### Issue Summary

When creating a new root key, under the Workspace permissions, the permission name overlaps with the permission description on smaller width windows. 

### Steps to Reproduce

1. Log into Unkey dashboard
2. Navigate to Settings > Root Key > Create New Root Key
3. Scroll down to Workspace [permissions]
4. Adjust browser size to be smaller
5. Observe description <> permission name (checkboxes) overlapping

### Expected behavior

Permission names should overflow or wrap to the next line 

### Other information

_No response_

### Screenshots

Screenshot 2024-09-23 at 1 37 25 PM

### Version info

```markdown
- OS: Sonoma 14.4
- Node: 20.17.0
- npm: 10.8.2
```

### PR DESCRIPTION
**Pull request by harshsbhat**
## What does this PR do?

image

Fixes #2125 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [ ] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Updated the description text for the permission toggle to improve clarity.

- **Style**
	- Adjusted the layout of the PermissionToggle component for better responsiveness across different screen sizes.
	- Enhanced the display of the description text for improved visual alignment.
	- Reformatted the `keywords` and `files` fields in multiple package.json files for consistency.

### CODE REVIEW

**Comment by chronark** [comment]
CleanShot 2024-09-24 at 09 35 10@2x
it still seems to happen, I just tried your PR

**Comment by harshsbhat** [comment]
image
After recent changes.

**Comment by harshsbhat** [comment]
> CleanShot 2024-09-24 at 09 35 10@2x it still seems to happen, I just tried your PR

it was happening for just one permission. Breaking the permission name didn't look good either. w-full looks decent I have pushed those changes

**Comment by mcstepp** [comment]
@chronark what do you think about having the permission description flow underneath the permission name at smaller screens?

**Comment by chronark** [comment]
> @chronark what do you think about having the permission description flow underneath the permission name at smaller screens?

that would be nice @mcstepp

**Comment by harshsbhat** [comment]
@chronark  @mcstepp 

image
this looks good, right?  But in my opinion, lets just keep this for mobile (smaller screens). Doesn't look too good on PC as it leaves too much whitespace on right hand side.

image

**Comment by chronark** [comment]
yes, only for small screens

also I think there's a max width or something we need to remove on small screens, there's plenty of space, yet we're showing 2 lines here
CleanShot 2024-09-24 at 16 12 03@2x

**Comment by harshsbhat** [comment]
yes, I just quickly added flex-col to see how it looks. I will push in a few minutes

**Comment by harshsbhat** [comment]
image


Latest changes @chronark

**Comment by chronark** [comment]
what if we align the text?

```
[ ] TITLE
    description
```

wdyt?

**Comment by harshsbhat** [comment]
@chronark

**Comment by harshsbhat** [comment]
image

**Comment by harshsbhat** [comment]
@chronark 

image

LGTM. wdyt? Should I push this?

**Comment by chronark** [comment]
yes please

**Comment by harshsbhat** [comment]
> yes please

done

**Review by chronark — CHANGES_REQUESTED** [review]
This messes up the alignment of category descriptions

Before:
CleanShot 2024-09-26 at 13 30 16@2x

After:
CleanShot 2024-09-26 at 13 29 36@2x

Why did you remove the `items-center`?

**Comment by harshsbhat** [comment]
> This messes up the alignment of category descriptions
> 
> Before:
> CleanShot 2024-09-26 at 13 30 16@2x
> 
> After:
> CleanShot 2024-09-26 at 13 29 36@2x
> 
> Why did you remove the `items-center`?

I accidentally removed it and didn't realise it as the changes in ui were very minimal. I will do the changes and push asap

**Comment by harshsbhat** [comment]
@chronark  should work now

**Comment by chronark** [comment]
CleanShot 2024-09-26 at 19 20 28@2x
it's still misaligned

**Comment by harshsbhat** [comment]
It's probably because I was referring to the live app. Which also has this misalignment.
image

**Comment by harshsbhat** [comment]
@chronark 


image



this issue I should have solved in #2062. As we are using `label={<span className="text-base font-bold">{category}</span>}` for the Select all buttons which is causing the alignment issues.

**Comment by chronark** [comment]
> It's probably because I was referring to the live app. Which also has this misalignment. image

wdym?

it's aligned in prod
CleanShot 2024-09-26 at 21 30 54@2x

**Comment by harshsbhat** [comment]
The SS you shared is for smaller screens.  I think this PR is ready for review.

BIGGER SCREENS:

image

SMALLER SCREENS:

image

**Comment by chronark** [comment]
Yes the previous screenshot was on a smaller screen, but it's also correctly aligned on large screens in prod
CleanShot 2024-09-27 at 09 19 22@2x

**Comment by chronark** [comment]
I never said this explicitely, but I mean center-aligned, the `items-center` you removed is very much needed

**Comment by harshsbhat** [comment]
> I never said this explicitely, but I mean center-aligned, the `items-center` you removed is very much needed
> 

it's required for a PC ( it makes just a little difference)

**Comment by chronark** [comment]
I'm sorry, what's `PC`?

**Comment by harshsbhat** [comment]
> I'm sorry, what's `PC`?

ah, I meant longer screen ( PC screen ). My bad should have been more clear about it

**Comment by harshsbhat** [comment]
> I'm sorry, what's `PC`?

ah, I meant longer screen ( PC screen ). My bad should have been more clear about it

**Comment by harshsbhat** [comment]
> I'm sorry, what's `PC`?

ah, I meant longer screen ( PC screen ). My bad should have been more clear about it

**Comment by chronark** [comment]
What's the status here?
I appreciate your eagerness for new issues, but let's try to close a few of your existing ones first

I just checked and it's not center aligned yet
CleanShot 2024-10-03 at 12 31 04@2x

**Comment by harshsbhat** [comment]
image
 
 
 It should be good now @chronark

**Review by chronark — APPROVED** [review]

**Comment by harshsbhat** [comment]
Did it fail any build?

**Review by chronark — APPROVED** [review]

**Pull request merged**
