### PR TITLE
chore: add internal package called @unkey/vault

### PR DESCRIPTION
**Pull request by harshsbhat**
## What does this PR do?

Adds a new internal library called `@unkey/vault ` with encryption and decryption so that we can connect dashboard to the vault

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Test A:
You can import this using the following line and use it in the dashboard
`import { type EncryptRequest, type RequestContext, Vault } from "@unkey/vault";`

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Introduced the `@unkey/vault` package for encryption and decryption operations.
	- Added functionality for encrypting and decrypting data through the `Vault` class, including methods for single and bulk operations.

- **Chores**
	- Updated the `@unkey/dashboard` project to include the new `@unkey/vault` dependency.

### CODE REVIEW

**Review by chronark — CHANGES_REQUESTED** [review]
This is essentially a copy of https://github.com/unkeyed/unkey/blob/main/apps/api/src/pkg/vault.ts right?

As part of this PR, could you remove it in the api and hook it up to use the shared library?

**Comment by harshsbhat** [comment]
> This is essentially a copy of https://github.com/unkeyed/unkey/blob/main/apps/api/src/pkg/vault.ts right?
> 
> As part of this PR, could you remove it in the api and hook it up to use the shared library?

Makes sense. That would reduce repeated code.

**Comment by harshsbhat** [comment]
> This is essentially a copy of https://github.com/unkeyed/unkey/blob/main/apps/api/src/pkg/vault.ts right?
> 
> As part of this PR, could you remove it in the api and hook it up to use the shared library?

@chronark what about metrics? We probably don't need it for the dashboard. But as the library is shared we would need to include them regardless right?

**Comment by harshsbhat** [comment]
> https://github.com/unkeyed/unkey/blob/main/apps/api/src/pkg/metrics/interface.ts
> 
> 
> 
> it's a very small interface, we can just copy that as well and make it optional

why optional? we don't need it for the dashboard but having it won't hurt right?

**Review by chronark — APPROVED** [review]

**Review by chronark — APPROVED** [review]

**Comment by harshsbhat** [comment]
@chronark  I was planning to work on this after we were done with the hackathon. Considering this one is going to require a lot of reviews from you guys which might not be possible right now during oss.gg. Hope that is fine/

**Comment by harshsbhat** [comment]
ah, you did the requested changes and merged it lol. My bad.

**Pull request merged**
