### PR TITLE
feat(dashboard): URL state synchronization for `/settings/root-keys/new` route

### LINKED ISSUE #2147: Linking permissions when creating root keys
### Preliminary Checks

- [X] I have reviewed https://unkey.com/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Is your feature request related to a problem? Please describe.

It's annoying to tell users in docs what perms to add and is a bad experience for the user cause they need to cross reference. Rather they should click on a link like `/settings/root-keys?permissions=api.*.create,key.*.verify` and can move on quickly

### Describe the solution

A user clicks on a link and it automatically selects the required permissions, all they need to is add a name and hit "create"
required permissions are stored in query params and the correct permission checkboxes are checked when the user navigates there.

We already use `nuqs` for query param parsing, I'd like to use it here too

### Describe alternatives you have considered (if any)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by unrenamed**
## What does this PR do?

Utilizes `nuqs` to establish two-way synchronization between URL query parameters and the page for creating a new root key. The `permissions` query parameter value corresponds to both workspace permissions and any scoped permissions for existing APIs, if available.

Fixes #2147 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
  - Navigate to the dashboard's /settings/root-keys/new page.
  - Select permissions from either or both the "Workspace Permissions" and "API-Specific Permissions" sections.
  - Verify that the selected permissions are reflected in the URL as query parameters.
- Test B
  - Copy the URL generated in Test A.
  - Open a new browser tab and paste the URL.
  - Ensure that the /settings/root-keys/new page loads with the permissions from the URL query parameters automatically selected in the permissions tree.
 
### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [ ] Ran `pnpm fmt`
- [ ] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Enhanced permissions handling with improved state management across navigation.
	- Introduced a new parser for unkeyed permissions to ensure safe query value parsing.

- **Improvements**
	- Updated rendering logic for permissions selection to reflect the new state structure.
	- Modified `TooltipTrigger` component for better tooltip trigger area structure.
	- Optimized performance with a more efficient state initialization approach.

### CODE REVIEW

**Review by chronark — CHANGES_REQUESTED** [review]
Works great, the only issue is that it's very easy to miss if an api scoped permission was checked cause the card doesn't expand by default

Could you expand all api cards if there's at least one checked permission?

https://share.cleanshot.com/mmKQRjTG

**Comment by unrenamed** [comment]
While working on this PR, I noticed other places causing rehydration issues, likely due to HTML semantics violations or incorrect use of the Radix UI API (e.g., a <button> inside a <button>; see [TooltipTrigger API](https://www.radix-ui.com/primitives/docs/components/tooltip#trigger)). The fix is to use the asChild prop for Radix components triggering these errors. I've fixed this in one place in this PR. 

But, it might be worth opening a separate issue for this, though it's not critical right now. WDYT, @chronark?

**Comment by unrenamed** [comment]
> Works great, the only issue is that it's very easy to miss if an api scoped permission was checked cause the card doesn't expand by default
> 
> Could you expand all api cards if there's at least one checked permission?
> 
> https://share.cleanshot.com/mmKQRjTG

Good catch! Sure, I'll look into this.

**Comment by chronark** [comment]
> While working on this PR, I noticed other places causing rehydration issues, likely due to HTML semantics violations or incorrect use of the Radix UI API (e.g., a inside a ; see [TooltipTrigger API](https://www.radix-ui.com/primitives/docs/components/tooltip#trigger)). The fix is to use the asChild prop for Radix components triggering these errors. I've fixed this in one place in this PR.
> 
> But, it might be worth opening a separate issue for this, though it's not critical right now. WDYT, @chronark?

Huh I didn't see this before
Could you create an issue for this, @unrenamed ?
I was never able to figure out what we did wrong and ignored it :/

**Review by chronark — APPROVED** [review]

**Comment by chronark** [comment]
The O(1) optimization is probably overkill, outside of some testing workspaces, nobody has more than a handful of apis, but it doesn't hurt I suppose.

**Review by chronark — APPROVED** [review]

**Comment by unrenamed** [comment]
> The O(1) optimization is probably overkill, outside of some testing workspaces, nobody has more than a handful of apis, but it doesn't hurt I suppose.

If a malicious user repeats permissions in the URL, the m * n solution could show its downside with exponential growth. The current solution, using a Set for uniqueness, should perform better in such cases. 

You are right. I seem to be pulling things out of thin air though 😅. If anyone experiences a performance downgrade, it would be the malicious user themselves 😄

**Comment by unrenamed** [comment]
> > While working on this PR, I noticed other places causing rehydration issues, likely due to HTML semantics violations or incorrect use of the Radix UI API (e.g., a inside a ; see [TooltipTrigger API](https://www.radix-ui.com/primitives/docs/components/tooltip#trigger)). The fix is to use the asChild prop for Radix components triggering these errors. I've fixed this in one place in this PR.
> > But, it might be worth opening a separate issue for this, though it's not critical right now. WDYT, @chronark?
> 
> Huh I didn't see this before Could you create an issue for this, @unrenamed ? I was never able to figure out what we did wrong and ignored it :/

yep, will do

**Pull request merged**
