### PR TITLE
feat: [🕹️] Record your onboarding and first steps with Unkey 

### LINKED ISSUE #2248: [🕹️] Record your onboarding and first steps with Unkey
**This issue can be done multiple times, you do not need to `/assign` yourself, just create the PR**

### Points

150 - 300

### Description

Record yourself going through the setup of Unkey for the first time and provide feedback. Depending on how much feedback you provide, we’ll assign 150 or 300 points.
You do not need to show your face if you don’t want to but voice is required. Please say out loud what you’re thinking or expecting as you go.

**What should be included:**
- Sign up
- Going through the onboarding
- Integrating Unkey into your app and either verify a key or use the ratelimiter

If you get stuck and can not do all of them, please report that. That’s probably the best feedback you can provide.
Proof:

### Provide proof that you've completed the task

Open a PR with a link to your video (youtube, loom, google drive…), if you have more feedback that is not mentioned in the video, please add it in the PR as well.
Add a line to [oss.gg/6_record_onboarding.md](https://github.com/unkeyed/unkey/blob/main/oss.gg/6_record_onboarding.md)

### PR DESCRIPTION
**Pull request by Ionfinisher**
## What does this PR do?
Solve the record your onboarding oss.gg challenge

Fixes #2248

Loom recording video link: https://www.loom.com/share/062a281f62d647448bf6f60fef4d6259?sid=cb77c751-f539-4e5e-bb63-69085518a2cf

Additional feedback:
It's pretty easy to be loast In the order things should be done to accomplish a task. There should be different onboardings specific to each task you can accomplish with unkey. Beside that, there are some minor UI bugs as toast not disapearing and the navbar overlaping a toolpit. Sorry again for the quality and hopefully this helps.

## Summary by CodeRabbit

- **Documentation**
	- Updated entry in the onboarding document with a new date and author.

### CODE REVIEW

**Comment by chronark** [comment]
Thank you!
I'll leave this open for now until the team gets a chance to look at it
don't worry we'll make sure give you points before the end of the month

**Comment by chronark** [comment]
@Ionfinisher just took a quick glance, **please take down the loom asap**, you leaked your notes which seem to contain some sensitive information

**Comment by Ionfinisher** [comment]
ok will do thanks alot

**Comment by Ionfinisher** [comment]
Should I record anothe one? @chronark

**Comment by chronark** [comment]
No that's overkill, could you cut out the part with the secrets and either reupload or dm me on our discord?
https://unkey.com/discord

**Comment by pantharshit007** [comment]
@Ionfinisher do you still have the recording?

**Comment by chronark** [comment]
Thanks @Ionfinisher

**Pull request merged**
