### PR TITLE
feat: add mysql adapter

### LINKED ISSUE #490: Allow using local mysql as well as planetscale
### Preliminary Checks

- [X] I have reviewed https://unkey.dev/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Description

An switch of some sort here should be enough to allow you to run the web app against any mysql db

https://github.com/unkeyed/unkey/blob/main/apps/web/lib/db.ts

### PR DESCRIPTION
**Pull request by G3root**
## Type of change

- [ ] 🐛 Bug fix
- [x] 🌟 New feature
- [x] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation

## Description

fixes #490

### Before this PR

{Please add a screenshot here}

### After this PR

{Please add a screenshot here}

### CODE REVIEW

**Comment by G3root** [comment]
TODO

- [ ] check whether all things work correctly
- [ ] make changes in the agent sql driver

**Comment by KartikSoneji** [comment]
Maybe it's better to switch automatically based on `DATABASE_HOST.endsWith("psdb.cloud")` ?

**Comment by chronark** [comment]
> Maybe it's better to switch automatically based on `DATABASE_HOST.endsWith("psdb.cloud")` ?

This feels a bit magical, I prefer the explicitly of a toggle flag

**Comment by KartikSoneji** [comment]
> > Maybe it's better to switch automatically based on `DATABASE_HOST.endsWith("psdb.cloud")` ?
> 
> This feels a bit magical, I prefer the explicitly of a toggle flag

Magic is nice :)

**Comment by chronark** [comment]
@G3root have you verified this will actually run in edge functions?

**Comment by G3root** [comment]
Tried playing with this, `mysql2` isn't edge ready. 
One of the blockers is db call used in middleware.ts which is edge only

**Comment by chronark** [comment]
yeah, and our trpc runs in edge too

**Comment by chronark** [comment]
added a workaround for CI, unfortunately it won't work when developing nextjs

**Pull request closed without merging**
