### PR TITLE
chore: Next.js Pay-as-you-Go starter kit [SIDE QUEST]

### PR DESCRIPTION
**Pull request by unrenamed**
## What does this PR do?

Adds a starter kit showcasing how to leverage Unkey API to implement Pay-as-you-Go system in your Next.js app powered by Supabase. https://github.com/unrenamed/unkey-nextjs-pay-as-you-go

image

Fixes #2150

## Summary by CodeRabbit

- **New Features**
	- Added new templates for Unkey integration with Flask, Django, Rust (Axum and Actix), and Deno frameworks.
	- Introduced a starter template for Unkey route protection on Cloudflare workers.
	- Launched a Next.js Unkey Pay-as-you-Go starter kit.
	- Included a live link for cost-based rate limiting template.

- **Documentation**
	- Updated the "Your turn" section with new template entries and guidelines for submissions.

### CODE REVIEW

**Comment by chronark** [comment]
small nitpick: switch to lightmode and our logo is gone :D

could you use this svg?
https://go.unkey.com/logo

**Comment by chronark** [comment]
and can you help me try it out?
what am I doing wrong?

I just went to the signup page of your hosted example

CleanShot 2024-10-13 at 11 31 12@2x

**Comment by unrenamed** [comment]
@chronark I think this is related to how Supabase auth filters "unauthorized" email domains to prevent spam, bots, etc. This should be configurable, but I haven't checked that yet. It definitely supports `@gmail.com` domain at the moment.

**Comment by unrenamed** [comment]
I can try to use a free Resend account as a custom SMTP to to provide additional email capacity for demo testers. Will do that later today. https://resend.com/blog/how-to-configure-supabase-to-send-emails-from-your-domain

**Comment by chronark** [comment]
don't sweat it, a disclaimer that only gmail works would be fine too I think

**Comment by chronark** [comment]
update: my gmail doesn't work either, same error

**Comment by unrenamed** [comment]
> update: my gmail doesn't work either, same error

I'll add a custom SMTP then 😃

**Comment by unrenamed** [comment]
@chronark I've fixed the logo and another bug related to the app themes. 

As for the custom SMTP, I'm afraid I cannot fix that at the moment. Apparently, Resend does not allow to integrate Supabase using free SMTP services and I don't have a custom domain to register within Resend account.

I can remove the links to the demo app deployed to Vercel to not confuse anyone. The starter kit can still be cloned and run locally.

**Comment by chronark** [comment]
yeah that's probably best. It's a shame, but advertising it when it's not usable would be frustrating

**Comment by unrenamed** [comment]
Yeah, this is exactly why I should remove it. My bad, I haven't tested this part thoroughly beforehand. 

Meanwhile, feel free to test it locally. The screenshot doesn't actually cover the core area of the app 😅

**Comment by unrenamed** [comment]
@chronark I removed all links to the live demo from the code base and repository page.

**Review by chronark — APPROVED** [review]

**Comment by unrenamed** [comment]
@chronark Thanks for merging this. Feel free to review my other templates when you get a chance:

https://github.com/unkeyed/unkey/pull/2420
https://github.com/unkeyed/unkey/pull/2376

**Comment by unrenamed** [comment]
@chronark just noticed `404 not found` on the template page

image

**Comment by unrenamed** [comment]
cc @chronark

**Pull request merged**
