### PR TITLE
docs: Quest complete

### PR DESCRIPTION
**Pull request by ShreyasLakhani**
## What does this PR do?

Fixes # (issue)

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

image
image

## Summary by CodeRabbit

- **Removed Features**
	- The template filtering and display functionality has been removed, eliminating the associated user interface elements.

- **Documentation Updates**
	- Added a new participant entry for Shreyans Lakhani in the Unkey X account list.
	- Updated the "Starry-eyed Supporter" quest documentation with a new participant entry for Shreyas Lakhani.

### CODE REVIEW

**Comment by chronark** [comment]
why does this delete a file?

**Comment by ShreyasLakhani** [comment]
@chronark review this PR

**Review by chronark — CHANGES_REQUESTED** [review]
don't delete files

**Comment by ShreyasLakhani** [comment]
@chronark  Will open new PR and closing this PR.

**Pull request closed without merging**
